In [66]:
import numpy as np
count = 0

In [67]:
A = np.array(
    [[1,2,3],
    [4,5,6],
    [7,8,9]]
)

In [68]:
A.shape

(3, 3)

In [69]:
A.dtype

dtype('int32')

In [70]:
B = np.array(
    [[1.3,2.5,3.5],
    [4.5,5.3,6.5],
    [7.5,8.5,9.3]]
).astype("float32")

In [71]:
B.shape

(3, 3)

In [72]:
B.dtype

dtype('float32')

In [73]:
np.save("int.npy",A,allow_pickle=True)
np.save("float.npy",B,allow_pickle=True)

In [74]:
import tensorflow as tf

In [75]:
int_file = tf.io.read_file("int.npy")
float_file = tf.io.read_file("float.npy")

In [76]:
int_file

<tf.Tensor: shape=(), dtype=string, numpy=b"\x93NUMPY\x01\x00v\x00{'descr': '<i4', 'fortran_order': False, 'shape': (3, 3), }                                                          \n\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00\t\x00\x00\x00">

In [77]:
float_file

<tf.Tensor: shape=(), dtype=string, numpy=b"\x93NUMPY\x01\x00v\x00{'descr': '<f4', 'fortran_order': False, 'shape': (3, 3), }                                                          \nff\xa6?\x00\x00 @\x00\x00`@\x00\x00\x90@\x9a\x99\xa9@\x00\x00\xd0@\x00\x00\xf0@\x00\x00\x08A\xcd\xcc\x14A">

In [110]:
def process(raw, option, sizee, shapee): #map_func
    #extract the 2d array and the label
    if option == 1:  img = tf.io.decode_raw(raw,tf.float32)
    else:
        img = tf.io.decode_raw(raw,tf.int32)
    print("----------------------------------------------------------------------------------------------------------- decoded")
    print(img)
    img = tf.slice(img,begin=[1024//32],size=sizee) # begin <- 1024//complex64
    print("----------------------------------------------------------------------------------------------------------- sliced")
    print(img)
    img = tf.reshape(img,shapee)
    print("----------------------------------------------------------------------------------------------------------- reshaped")
    print(img)
    return img

In [111]:
process(int_file,0,[9],(3,3))
print(A)

----------------------------------------------------------------------------------------------------------- decoded
tf.Tensor(
[1297436307      88400  662372470 1668506980  540682098  879311911
  656419879 1953656678 1601069426 1701081711  540682098 1936482630
  656419941 1885431923  540682085  539767592  539765043  538976381
  538976288  538976288  538976288  538976288  538976288  538976288
  538976288  538976288  538976288  538976288  538976288  538976288
  538976288  169877536          1          2          3          4
          5          6          7          8          9], shape=(41,), dtype=int32)
----------------------------------------------------------------------------------------------------------- sliced
tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
----------------------------------------------------------------------------------------------------------- reshaped
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [112]:
process(float_file,1,[9],(3,3))
print(B)

----------------------------------------------------------------------------------------------------------- decoded
tf.Tensor(
[2.2366853e+08 1.2387478e-40 3.4833497e-15 4.4898648e+21 1.5767864e-19
 2.1442303e-07 2.2228396e-15 7.6830766e+31 1.7177136e+19 6.7425655e+22
 1.5767864e-19 1.8727951e+31 2.2228527e-15 2.7904159e+29 1.5767847e-19
 1.4585893e-19 1.4582598e-19 1.3563277e-19 1.3563156e-19 1.3563156e-19
 1.3563156e-19 1.3563156e-19 1.3563156e-19 1.3563156e-19 1.3563156e-19
 1.3563156e-19 1.3563156e-19 1.3563156e-19 1.3563156e-19 1.3563156e-19
 1.3563156e-19 7.7097618e-33 1.3000000e+00 2.5000000e+00 3.5000000e+00
 4.5000000e+00 5.3000002e+00 6.5000000e+00 7.5000000e+00 8.5000000e+00
 9.3000002e+00], shape=(41,), dtype=float32)
----------------------------------------------------------------------------------------------------------- sliced
tf.Tensor([1.3 2.5 3.5 4.5 5.3 6.5 7.5 8.5 9.3], shape=(9,), dtype=float32)
---------------------------------------------------------------------

In [123]:
def make_and_decode_float(count,array,size,shape):
    np.save("sep_"+str(count), array, allow_pickle=True)
    img = tf.io.read_file("sep_"+str(count)+".npy")
    a = process(img,1,size,shape)
    print("----------------------------------------------------------------------------------------------------------- the original array")
    print(array)
    print("----------------------------------------------------------------------------------------------------------- difference")
    print(a.numpy()-array)

In [124]:
make_and_decode_float(count,B,[9],(3,3))
count = count + 1

----------------------------------------------------------------------------------------------------------- decoded
tf.Tensor(
[2.2366853e+08 1.2387478e-40 3.4833497e-15 4.4898648e+21 1.5767864e-19
 2.1442303e-07 2.2228396e-15 7.6830766e+31 1.7177136e+19 6.7425655e+22
 1.5767864e-19 1.8727951e+31 2.2228527e-15 2.7904159e+29 1.5767847e-19
 1.4585893e-19 1.4582598e-19 1.3563277e-19 1.3563156e-19 1.3563156e-19
 1.3563156e-19 1.3563156e-19 1.3563156e-19 1.3563156e-19 1.3563156e-19
 1.3563156e-19 1.3563156e-19 1.3563156e-19 1.3563156e-19 1.3563156e-19
 1.3563156e-19 7.7097618e-33 1.3000000e+00 2.5000000e+00 3.5000000e+00
 4.5000000e+00 5.3000002e+00 6.5000000e+00 7.5000000e+00 8.5000000e+00
 9.3000002e+00], shape=(41,), dtype=float32)
----------------------------------------------------------------------------------------------------------- sliced
tf.Tensor([1.3 2.5 3.5 4.5 5.3 6.5 7.5 8.5 9.3], shape=(9,), dtype=float32)
---------------------------------------------------------------------

In [125]:
import random

C = np.array(
    [[random.random() for i in range(300)] for k in range(500)]
).astype("float32")

In [126]:
C.shape

(500, 300)

In [127]:
make_and_decode_float(count,C,[150000],(500,300))
count = count + 1

----------------------------------------------------------------------------------------------------------- decoded
tf.Tensor(
[2.2366853e+08 1.2387478e-40 3.4833497e-15 ... 8.2270503e-01 3.9547831e-01
 5.5033779e-01], shape=(150032,), dtype=float32)
----------------------------------------------------------------------------------------------------------- sliced
tf.Tensor([0.6773843  0.8097628  0.62143683 ... 0.82270503 0.3954783  0.5503378 ], shape=(150000,), dtype=float32)
----------------------------------------------------------------------------------------------------------- reshaped
tf.Tensor(
[[0.6773843  0.8097628  0.62143683 ... 0.73585117 0.66729724 0.37802505]
 [0.5414975  0.70718676 0.8667719  ... 0.9401581  0.07105435 0.5676022 ]
 [0.07628904 0.9995463  0.87812334 ... 0.42561853 0.09029406 0.5037247 ]
 ...
 [0.46935782 0.9503901  0.7297636  ... 0.3245213  0.9775699  0.5655722 ]
 [0.6933546  0.04625065 0.4906977  ... 0.35136563 0.6222113  0.9374679 ]
 [0.15265927 0.170654

In [128]:
dataset = tf.io.read_file("C:/Users/KSAI/jaewon_projectfolder/music-discern/Datasets/MTGJamendo/processed/fold3/3900_music_1.npy")
l = process(dataset,1,[345*513],(513,345))


----------------------------------------------------------------------------------------------------------- decoded
tf.Tensor(
[ 2.2366853e+08  1.2387478e-40  3.4833497e-15 ... -2.0907646e+01
 -2.0907782e+01 -2.0907799e+01], shape=(177017,), dtype=float32)
----------------------------------------------------------------------------------------------------------- sliced
tf.Tensor([-11.836594 -11.514672  -9.778002 ... -20.907646 -20.907782 -20.907799], shape=(176985,), dtype=float32)
----------------------------------------------------------------------------------------------------------- reshaped
tf.Tensor(
[[-11.836594  -11.514672   -9.778002  ... -15.733987  -15.992006
  -17.675846 ]
 [-20.102444  -18.307434  -17.578178  ... -12.266478  -11.883055
  -12.0802355]
 [ -9.8171625  -8.7040415 -12.807374  ... -10.349186   -7.174571
   -5.1632347]
 ...
 [-64.19252   -65.1323    -64.39188   ... -26.507368  -25.728247
  -26.729296 ]
 [-25.96288   -24.316513  -29.655058  ... -11.402594   -6.78

In [129]:
data = np.load("C:/Users/KSAI/jaewon_projectfolder/music-discern/Datasets/MTGJamendo/processed/fold3/3900_music_1.npy")
make_and_decode_float(count,data,[513*345],(513,345))
count = count + 1

----------------------------------------------------------------------------------------------------------- decoded
tf.Tensor(
[ 2.2366853e+08  1.2387478e-40  3.4833497e-15 ... -2.0907646e+01
 -2.0907782e+01 -2.0907799e+01], shape=(177017,), dtype=float32)
----------------------------------------------------------------------------------------------------------- sliced
tf.Tensor([-11.836594 -11.514672  -9.778002 ... -20.907646 -20.907782 -20.907799], shape=(176985,), dtype=float32)
----------------------------------------------------------------------------------------------------------- reshaped
tf.Tensor(
[[-11.836594  -11.514672   -9.778002  ... -15.733987  -15.992006
  -17.675846 ]
 [-20.102444  -18.307434  -17.578178  ... -12.266478  -11.883055
  -12.0802355]
 [ -9.8171625  -8.7040415 -12.807374  ... -10.349186   -7.174571
   -5.1632347]
 ...
 [-64.19252   -65.1323    -64.39188   ... -26.507368  -25.728247
  -26.729296 ]
 [-25.96288   -24.316513  -29.655058  ... -11.402594   -6.78

In [130]:
D = np.array(
    [[-1 * random.random()-15 for i in range(300)] for k in range(500)]
).astype("float32")

In [131]:
make_and_decode_float(count,D,[150000],(500,300))
count = count + 1

----------------------------------------------------------------------------------------------------------- decoded
tf.Tensor(
[ 2.23668528e+08  1.23874784e-40  3.48334973e-15 ... -1.51147194e+01
 -1.51174755e+01 -1.59006796e+01], shape=(150032,), dtype=float32)
----------------------------------------------------------------------------------------------------------- sliced
tf.Tensor(
[-15.125241  -15.992001  -15.024055  ... -15.114719  -15.1174755
 -15.90068  ], shape=(150000,), dtype=float32)
----------------------------------------------------------------------------------------------------------- reshaped
tf.Tensor(
[[-15.125241  -15.992001  -15.024055  ... -15.888538  -15.204943
  -15.5527   ]
 [-15.531994  -15.620288  -15.123414  ... -15.89663   -15.573779
  -15.052631 ]
 [-15.989295  -15.3203745 -15.077524  ... -15.702647  -15.739504
  -15.284553 ]
 ...
 [-15.29031   -15.238995  -15.874323  ... -15.642188  -15.003365
  -15.014249 ]
 [-15.454135  -15.527708  -15.488817  ... -15.

In [140]:
E = np.array(
    [[-1 * random.random()-15 for i in range(345)] for k in range(513)]
).astype("float32")

In [141]:
make_and_decode_float(count,E,[513*345],(513,345))
count = count + 1

----------------------------------------------------------------------------------------------------------- decoded
tf.Tensor(
[ 2.23668528e+08  1.23874784e-40  3.48334973e-15 ... -1.52463045e+01
 -1.53197756e+01 -1.52038355e+01], shape=(177017,), dtype=float32)
----------------------------------------------------------------------------------------------------------- sliced
tf.Tensor(
[-15.672331  -15.34857   -15.166176  ... -15.2463045 -15.319776
 -15.2038355], shape=(176985,), dtype=float32)
----------------------------------------------------------------------------------------------------------- reshaped
tf.Tensor(
[[-15.672331  -15.34857   -15.166176  ... -15.489953  -15.644239
  -15.345528 ]
 [-15.071802  -15.237648  -15.378071  ... -15.488124  -15.857299
  -15.982594 ]
 [-15.78959   -15.106565  -15.1150675 ... -15.285022  -15.079334
  -15.351436 ]
 ...
 [-15.320779  -15.689777  -15.475434  ... -15.336412  -15.955624
  -15.976853 ]
 [-15.358331  -15.90962   -15.18862   ... -15.7