In [66]:
import numpy as np
count = 0

In [67]:
A = np.array(
    [[1,2,3],
    [4,5,6],
    [7,8,9]]
)

In [68]:
A.shape

(3, 3)

In [69]:
A.dtype

dtype('int32')

In [70]:
B = np.array(
    [[1.3,2.5,3.5],
    [4.5,5.3,6.5],
    [7.5,8.5,9.3]]
).astype("float32")

In [71]:
B.shape

(3, 3)

In [72]:
B.dtype

dtype('float32')

In [73]:
np.save("int.npy",A,allow_pickle=True)
np.save("float.npy",B,allow_pickle=True)

In [74]:
import tensorflow as tf

In [75]:
int_file = tf.io.read_file("int.npy")
float_file = tf.io.read_file("float.npy")

In [76]:
int_file

<tf.Tensor: shape=(), dtype=string, numpy=b"\x93NUMPY\x01\x00v\x00{'descr': '<i4', 'fortran_order': False, 'shape': (3, 3), }                                                          \n\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00\t\x00\x00\x00">

In [77]:
float_file

<tf.Tensor: shape=(), dtype=string, numpy=b"\x93NUMPY\x01\x00v\x00{'descr': '<f4', 'fortran_order': False, 'shape': (3, 3), }                                                          \nff\xa6?\x00\x00 @\x00\x00`@\x00\x00\x90@\x9a\x99\xa9@\x00\x00\xd0@\x00\x00\xf0@\x00\x00\x08A\xcd\xcc\x14A">

In [93]:
def process(raw, option, sizee, shapee): #map_func
    #extract the 2d array and the label
    if option == 1:  img = tf.io.decode_raw(raw,tf.float32)
    else:
        img = tf.io.decode_raw(raw,tf.int32)
    print("-----------------------------------------------------------------------------------------------------------")
    print(img)
    img = tf.slice(img,begin=[1024//32],size=sizee) # begin <- 1024//complex64
    print("-----------------------------------------------------------------------------------------------------------")
    print(img)
    img = tf.reshape(img,shapee)
    print("-----------------------------------------------------------------------------------------------------------")
    print(img)
    return img

In [94]:
process(int_file,0,[9],(3,3))
print(A)

-----------------------------------------------------------------------------------------------------------
tf.Tensor(
[1297436307      88400  662372470 1668506980  540682098  879311911
  656419879 1953656678 1601069426 1701081711  540682098 1936482630
  656419941 1885431923  540682085  539767592  539765043  538976381
  538976288  538976288  538976288  538976288  538976288  538976288
  538976288  538976288  538976288  538976288  538976288  538976288
  538976288  169877536          1          2          3          4
          5          6          7          8          9], shape=(41,), dtype=int32)
-----------------------------------------------------------------------------------------------------------
tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
-----------------------------------------------------------------------------------------------------------
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [95]:
process(float_file,1,[9],(3,3))
print(B)

-----------------------------------------------------------------------------------------------------------
tf.Tensor(
[2.2366853e+08 1.2387478e-40 3.4833497e-15 4.4898648e+21 1.5767864e-19
 2.1442303e-07 2.2228396e-15 7.6830766e+31 1.7177136e+19 6.7425655e+22
 1.5767864e-19 1.8727951e+31 2.2228527e-15 2.7904159e+29 1.5767847e-19
 1.4585893e-19 1.4582598e-19 1.3563277e-19 1.3563156e-19 1.3563156e-19
 1.3563156e-19 1.3563156e-19 1.3563156e-19 1.3563156e-19 1.3563156e-19
 1.3563156e-19 1.3563156e-19 1.3563156e-19 1.3563156e-19 1.3563156e-19
 1.3563156e-19 7.7097618e-33 1.3000000e+00 2.5000000e+00 3.5000000e+00
 4.5000000e+00 5.3000002e+00 6.5000000e+00 7.5000000e+00 8.5000000e+00
 9.3000002e+00], shape=(41,), dtype=float32)
-----------------------------------------------------------------------------------------------------------
tf.Tensor([1.3 2.5 3.5 4.5 5.3 6.5 7.5 8.5 9.3], shape=(9,), dtype=float32)
------------------------------------------------------------------------------------

In [96]:
def make_and_decode_float(count,array,size,shape):
    np.save("sep_"+str(count), array, allow_pickle=True)
    img = tf.io.read_file("sep_"+str(count)+".npy")
    a = process(img,1,size,shape)
    print("-----------------------------------------------------------------------------------------------------------")
    print(array)
    print("-----------------------------------------------------------------------------------------------------------")
    print(a-array)

In [97]:
make_and_decode_float(count,B,[9],(3,3))
count = count + 1

-----------------------------------------------------------------------------------------------------------
tf.Tensor(
[2.2366853e+08 1.2387478e-40 3.4833497e-15 4.4898648e+21 1.5767864e-19
 2.1442303e-07 2.2228396e-15 7.6830766e+31 1.7177136e+19 6.7425655e+22
 1.5767864e-19 1.8727951e+31 2.2228527e-15 2.7904159e+29 1.5767847e-19
 1.4585893e-19 1.4582598e-19 1.3563277e-19 1.3563156e-19 1.3563156e-19
 1.3563156e-19 1.3563156e-19 1.3563156e-19 1.3563156e-19 1.3563156e-19
 1.3563156e-19 1.3563156e-19 1.3563156e-19 1.3563156e-19 1.3563156e-19
 1.3563156e-19 7.7097618e-33 1.3000000e+00 2.5000000e+00 3.5000000e+00
 4.5000000e+00 5.3000002e+00 6.5000000e+00 7.5000000e+00 8.5000000e+00
 9.3000002e+00], shape=(41,), dtype=float32)
-----------------------------------------------------------------------------------------------------------
tf.Tensor([1.3 2.5 3.5 4.5 5.3 6.5 7.5 8.5 9.3], shape=(9,), dtype=float32)
------------------------------------------------------------------------------------

In [98]:
import random

C = np.array(
    [[random.random() for i in range(300)] for k in range(500)]
).astype("float32")

In [99]:
C.shape

(500, 300)

In [100]:
make_and_decode_float(count,C,[150000],(500,300))
count = count + 1

-----------------------------------------------------------------------------------------------------------
tf.Tensor(
[2.2366853e+08 1.2387478e-40 3.4833497e-15 ... 7.1931487e-01 4.8352534e-01
 8.2913250e-01], shape=(150032,), dtype=float32)
-----------------------------------------------------------------------------------------------------------
tf.Tensor([0.5055448  0.7467926  0.779614   ... 0.7193149  0.48352534 0.8291325 ], shape=(150000,), dtype=float32)
-----------------------------------------------------------------------------------------------------------
tf.Tensor(
[[0.5055448  0.7467926  0.779614   ... 0.019991   0.1351685  0.4664096 ]
 [0.71851885 0.37390026 0.4126564  ... 0.60745317 0.3797943  0.9431624 ]
 [0.5065413  0.29162502 0.69681144 ... 0.88051194 0.856127   0.76028526]
 ...
 [0.9717258  0.4970183  0.57587254 ... 0.8980578  0.07052182 0.2566921 ]
 [0.9414052  0.5951339  0.9941546  ... 0.75237626 0.57231104 0.2748247 ]
 [0.27668306 0.8721481  0.24679025 ... 0.7193

In [103]:
dataset = tf.io.read_file("C:/Users/KSAI/jaewon_projectfolder/music-discern/Datasets/MTGJamendo/processed/fold3/3900_music_1.npy")
l = process(dataset,1,[345*513],(513,345))


-----------------------------------------------------------------------------------------------------------
tf.Tensor(
[ 2.2366853e+08  1.2387478e-40  3.4833497e-15 ... -2.0907646e+01
 -2.0907782e+01 -2.0907799e+01], shape=(177017,), dtype=float32)
-----------------------------------------------------------------------------------------------------------
tf.Tensor([-11.836594 -11.514672  -9.778002 ... -20.907646 -20.907782 -20.907799], shape=(176985,), dtype=float32)
-----------------------------------------------------------------------------------------------------------
tf.Tensor(
[[-11.836594  -11.514672   -9.778002  ... -15.733987  -15.992006
  -17.675846 ]
 [-20.102444  -18.307434  -17.578178  ... -12.266478  -11.883055
  -12.0802355]
 [ -9.8171625  -8.7040415 -12.807374  ... -10.349186   -7.174571
   -5.1632347]
 ...
 [-64.19252   -65.1323    -64.39188   ... -26.507368  -25.728247
  -26.729296 ]
 [-25.96288   -24.316513  -29.655058  ... -11.402594   -6.7844286
   -7.253024 ]
 [ 

In [102]:
data = np.load("C:/Users/KSAI/jaewon_projectfolder/music-discern/Datasets/MTGJamendo/processed/fold3/3900_music_1.npy")
make_and_decode_float(count,data,[513*345],(513,345))
count = count + 1

-----------------------------------------------------------------------------------------------------------
tf.Tensor(
[ 2.2366853e+08  1.2387478e-40  3.4833497e-15 ... -2.0907646e+01
 -2.0907782e+01 -2.0907799e+01], shape=(177017,), dtype=float32)
-----------------------------------------------------------------------------------------------------------
tf.Tensor([-11.836594 -11.514672  -9.778002 ... -20.907646 -20.907782 -20.907799], shape=(176985,), dtype=float32)
-----------------------------------------------------------------------------------------------------------
tf.Tensor(
[[-11.836594  -11.514672   -9.778002  ... -15.733987  -15.992006
  -17.675846 ]
 [-20.102444  -18.307434  -17.578178  ... -12.266478  -11.883055
  -12.0802355]
 [ -9.8171625  -8.7040415 -12.807374  ... -10.349186   -7.174571
   -5.1632347]
 ...
 [-64.19252   -65.1323    -64.39188   ... -26.507368  -25.728247
  -26.729296 ]
 [-25.96288   -24.316513  -29.655058  ... -11.402594   -6.7844286
   -7.253024 ]
 [ 